services:
  - type: web
    name: hidden-gems-finder
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && apt-get update && apt-get install -y ffmpeg"
    startCommand: "gunicorn live_search_app:app --timeout 600"
    # We need to specify the region for the free plan
    region: oregon 
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11