services:
  - type: web
    name: video-similarity-tool
    env: python
    pythonVersion: "3.10" 
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn live_search_app:app --timeout 600"
